version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: solarTech
      MYSQL_ROOT_PASSWORD: root
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
